### ISSUE TITLE
[BUG] Circular Nameplates are not centered in the middle of the token

### ISSUE THREAD

**Issue by Zamrod** [p4535992/foundryvtt-border-control#1]
**Module Version:** v2.0.2

**Describe the bug**
In v9 circular nameplates were centered in the middle of the token. The reason circular nameplates got added is because of a request from me. The goal was to have the nameplate circle the token (either on the outside of the token or the inside with a negative nameplate radius. Unfortunately with V10, the nameplates now just center themselves around the normal location for nameplates so decreasing the radius doesn't put the nameplate inside the token, it just makes a smaller and smaller circle underneath the token. I have attached how it used to look in v9 and now it looks now.

**Screenshots**
![image](https://user-images.githubusercontent.com/12570777/228431068-e0139dec-0ad1-4026-a113-826f602cdff1.png)

![image](https://user-images.githubusercontent.com/12570777/228431320-60a1471a-d4dc-4805-b5c2-6cbd6e73b4c0.png)

**Foundry Version:** 
10,291

**Game System:** 
dnd5e

**Comment by p4535992** [comment]
This feature is been removed on 2.2.X use instead other modules with similar feature
