### ISSUE TITLE
Permanently borders only turn on if you mouse over each token

### ISSUE THREAD

**Issue by Zamrod** [p4535992/foundryvtt-border-control#3]
When the Permanent Borders setting is turned on, it only shows no borders on login, refresh or scene switch until you mouse over a token. Each token you mouse over gets a border that stays on permanently but every other token doesn't have one.

I would expect them to all be on constantly with this feature.

Foundry: 10.291
DnD5e 2.1.5
Border Control 2.0.2

**Comment by p4535992** [comment]
I close this ticket beacuse is referenced to the v10 and there is anotehr ticket about this for v11, the sad truth is i cannot solve this on v11 either
