### ISSUE TITLE
[REQUEST] Option to remove Border Control Toggler on the token right click

### ISSUE THREAD

**Issue by GambetTV** [p4535992/foundryvtt-border-control#4]
Inside each token's configuration settings you give us options for disabling/enabling their border. Personally I would find this to be enough, as I pretty much would never need to quickly toggle back and forth between their border being visible/invisible, and 99% of my tokens will always have their border visible at all times. Therefore I suggest an option that will disable the border control toggle button when you right click on tokens, so that we are forced to go into the Token's Configuration to change this.

By doing this, it'll clean up a lot of the clutter when you right click on a token. Personally I have a lot of modules that add buttons to this already, and this is just an unnecessary one for me. Thank you!

**Comment by p4535992** [comment]
There is a module setting for that ?
