### ISSUE TITLE
[BUG][v12] v2.2.3 permanently removes all borders on v12

### ISSUE THREAD

**Issue by GambetTV** [p4535992/foundryvtt-border-control#9]
I realize v12 isn't fully supported yet, though the manifest was updated suggesting there was some v12 support, so I thought I'd just make a bug report to help tracking. When the module is active, all tokens seem to have their borders removed, regardless of settings, and changing settings doesn't fix it.

**Comment by TheXeno30** [comment]
It looks like everything is working fine in V12 except that the border is somehow offset in relation to the token.
![image](https://github.com/user-attachments/assets/5ec84b95-13c1-45a3-b35d-cf486e229625)

Maybe this will help with the fix.
and thanks for a great module.

**Comment by Red5MT** [comment]
Any update on this issue? I hope the author is still working on this module.

**Comment by Red5MT** [comment]
You might try hitting up Clemente (Matheus Clemente). He has a much simpler border module called 'Token Border Width' that handles circular token borders just fine.

https://github.com/mclemente/fvtt-border-width

**Comment by Red5MT** [comment]
Looking good so far.
